apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-sykepengesoknad-pdfgen
  namespace: flex
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad-arkivering-oppgave
        - application: sykepengesoknad-altinn
