name: Bygg, publish og deploy
on:
  push:
env:
  APP: flex-sykepengesoknad-pdfgen
jobs:
  build-and-publish:
    name: Bygg, test og publiser docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.lag-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generer image
        id: lag-image
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "::set-output name=image::ghcr.io/navikt/$APP:$VERSION"
      - name: Docker login
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        if: github.ref_name == 'master' || startsWith(github.ref_name, 'dev-')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg og push Docker image
        if: github.ref_name == 'master' || startsWith(github.ref_name, 'dev-')
        run: |
          docker build . -f Dockerfile -t ${{ steps.lag-image.outputs.image }}
          docker push ${{ steps.lag-image.outputs.image }}

  snyk-docker:
    needs: build-and-publish
    uses: navikt/flex-github-actions-workflows/.github/workflows/snyk-docker.yml@master
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
    secrets: inherit

  nais-deploy:
    needs: build-and-publish
    uses: navikt/flex-github-actions-workflows/.github/workflows/nais-deploy-dev-og-prod.yml@master
    with:
      image: ${{ needs.build-and-publish.outputs.image }}
      app: ${{ inputs.app }}
    secrets: inherit
